#------------------------------------------------------------------------------------------------------------------------------
# Module ECG_Config
#
# JSON-based parameter configuration for the ECG code, replacing the manual
# post-include mutation of ECG_Param module globals in notebooks.
#
# A single JSON file (default "ecg_config.json") fully describes a run:
#
#   {
#     "setup": {
#       "copy":  [ "../ECG_Julia/ECG_Param.jl", "..." ],   // copied into the working directory
#       "clean": [ "swapfile.dat", "..." ]                 // removed from the working directory if present
#     },
#     "ECG_Param": { "MatElem_method": "CGL0", ... },      // module-level settings of ECG_Param
#     "param0":    { "name": "HD+ molecular ion", ... },   // fields of ECG_Param.param0 (Init_param)
#     "actions":   [ { "Type": "BASIS_ENL", ... }, ... ]   // (optional) command script, alternate
#   }                                                       //   to the inout.txt action list
#
# The optional "actions" array (one object per action, "Type" = the action name)
# is turned into ECG_Init.action_list by data_init(); when present it replaces the
# action script read from inout.txt (the system + basis still come from inout.txt).
#
# The JSON file can be written by hand or generated by an external tool
# (e.g. a Python/Gradio user interface) — see save_config() for producing a
# template with all current values.
#
# Typical notebook usage:
#
#   include("../ECG_Julia/ECG_Config.jl")
#   cfg = ECG_Config.read_config("ecg_config.json")
#   ECG_Config.setup_workdir!(cfg)       # native-Julia file copies / cleanup
#   include("ECG_Param.jl")              # defaults
#   ECG_Config.apply!(cfg)               # overlay JSON values
#   include("ECG_Init.jl")
#   include("ECG.jl")
#   ok = ECG.do_action()
#------------------------------------------------------------------------------------------------------------------------------
module ECG_Config

using JSON

export read_config, setup_workdir!, apply!, load_config!, save_config, safe_cp, write_config_actions!

#------------------------------------------------------------------------------
# safe_cp() — Julia equivalent of Python's shutil.copy
# Copies src to dst (a file path or an existing directory), overwriting and
# preserving permissions (so a copied Fortran executable stays executable).
#------------------------------------------------------------------------------
function safe_cp(src::AbstractString, dst::AbstractString=".")
    isfile(src) || error("safe_cp: source file not found: $src")
    if isdir(dst)
        dst = joinpath(dst, basename(src))
    end
    Base.cp(src, dst; force=true)
    return dst
end

#------------------------------------------------------------------------------
# read_config() — parse the JSON configuration file
#------------------------------------------------------------------------------
# Path of the most recently read configuration file, remembered by read_config so
# ECG.do_action() can update its "actions" section before writing inout_1.txt.
const _config_file = Ref("")

function read_config(config_file::AbstractString="ecg_config.json")
    isfile(config_file) || error("read_config: configuration file not found: $config_file")
    _config_file[] = config_file
    return JSON.parsefile(config_file)
end

#------------------------------------------------------------------------------
# setup_workdir!() — copy the files listed in cfg["setup"]["copy"] into the
# working directory and remove the files listed in cfg["setup"]["clean"].
# Replaces the run(pipeline(`cp -f ...`)) / run(pipeline(`rm ...`)) notebook
# cells with portable native-Julia calls.
#
# Each "copy" entry is either
#   "path/to/file"                       → copied here under its own name, or
#   {"from": "path/to/file", "to": "x"}  → copied here as "x" (rename),
#     e.g. {"from": "../RGL1_1_F90/release/ecg", "to": "main"}.
#------------------------------------------------------------------------------
function setup_workdir!(cfg::AbstractDict; verbose::Bool=true)
    setup = get(cfg, "setup", nothing)
    setup === nothing && return

    for entry in get(setup, "copy", String[])
        if entry isa AbstractDict
            src = entry["from"]
            dst = entry["to"]
        else
            src = entry
            dst = "."
        end
        if isfile(src)
            dst = safe_cp(src, dst)
            verbose && println("setup_workdir! - copied $src -> $dst")
        else
            println("setup_workdir! - WARNING: source file not found, skipped: $src")
        end
    end

    for f in get(setup, "clean", String[])
        if isfile(f)
            rm(f; force=true)
            verbose && println("setup_workdir! - removed $f")
        end
    end
    return
end

#------------------------------------------------------------------------------
# _setvalue!() — assign with conversion to the declared field type, so JSON
# numbers land correctly in Int64/Float64/Bool fields.
#------------------------------------------------------------------------------
function _convert_to(T, v)
    T === Any && return v
    return convert(T, v)
end

#------------------------------------------------------------------------------
# apply!() — overlay the JSON values onto module ECG_Param:
#   cfg["ECG_Param"] → module-level globals
#   cfg["param0"]    → fields of the ECG_Param.param0 (Init_param) instance
# Unknown keys produce a clear warning instead of an error, so older config
# files keep working with newer code (and typos are visible).
#------------------------------------------------------------------------------
function apply!(cfg::AbstractDict; verbose::Bool=true)
    parent = parentmodule(@__MODULE__)          # Main (notebook) or ECG_Julia (package)
    isdefined(parent, :ECG_Param) || error("apply!: include(\"ECG_Param.jl\") before calling ECG_Config.apply!")
    P = parent.ECG_Param

    for (k, v) in get(cfg, "ECG_Param", Dict{String,Any}())
        sym = Symbol(k)
        if isdefined(P, sym)
            old = getproperty(P, sym)
            setproperty!(P, sym, _convert_to(typeof(old), v))
            verbose && println("apply! - ECG_Param.$k = $(repr(v))")
        else
            println("apply! - WARNING: unknown ECG_Param setting ignored: $k")
        end
    end

    p0 = P.param0
    T0 = typeof(p0)
    for (k, v) in get(cfg, "param0", Dict{String,Any}())
        sym = Symbol(k)
        if hasfield(T0, sym)
            setfield!(p0, sym, _convert_to(fieldtype(T0, sym), v))
            verbose && println("apply! - param0.$k = $(repr(v))")
        else
            println("apply! - WARNING: unknown param0 field ignored: $k")
        end
    end

    # cfg["actions"] (optional) — stored raw so ECG_Init.data_init() can turn it
    # into the action_list (alternate to the legacy inout.txt command script).
    if haskey(cfg, "actions")
        setproperty!(P, :config_actions, cfg["actions"])
        verbose && println("apply! - stored $(length(cfg["actions"])) action(s) into ECG_Param.config_actions")
    end
    return
end

#------------------------------------------------------------------------------
# load_config!() — convenience wrapper: read + setup_workdir! + apply!
# Call after include("ECG_Param.jl").
#------------------------------------------------------------------------------
function load_config!(config_file::AbstractString="ecg_config.json"; do_setup::Bool=true, verbose::Bool=true)
    cfg = read_config(config_file)
    do_setup && setup_workdir!(cfg; verbose=verbose)
    apply!(cfg; verbose=verbose)
    return cfg
end

#------------------------------------------------------------------------------
# Module-level ECG_Param settings that belong in a config file.
# (_EPS, Mini, param0 and other derived/internal values are excluded.)
#------------------------------------------------------------------------------
const ECG_PARAM_KEYS = [
    :verbose, :compute_H_S_method, :MatElem_method, :GSEPSolutionMethod,
    :GSEPIIS_Max_iter, :do_GSEPIIS, :do_Fortran,
    :outfile, :inout_file, :inout_F90_file, :param_file, :Mass_file,
    :PseudoCharge_file, :NonlinParam_file, :trace_file, :NonlinParam_file_F90,
    :NonlinParam_db_file, :read_param_file,
    :YOperatorStringLength, :max_print_H, :grad_k, :grad_l, :all_real,
    :overlap_Skl,
]

#------------------------------------------------------------------------------
# save_config() — write the current ECG_Param settings and param0 fields into
# a JSON file. Useful for generating a template config that an external UI
# (e.g. Gradio) or the user can edit.
#------------------------------------------------------------------------------
function save_config(config_file::AbstractString="ecg_config.json";
                     setup::AbstractDict=Dict{String,Any}(),
                     include_actions::Bool=true, verbose::Bool=true)
    parent = parentmodule(@__MODULE__)          # Main (notebook) or ECG_Julia (package)
    isdefined(parent, :ECG_Param) || error("save_config: include(\"ECG_Param.jl\") before calling ECG_Config.save_config")
    P = parent.ECG_Param

    ecg_param = Dict{String,Any}(
        String(k) => getproperty(P, k) for k in ECG_PARAM_KEYS if isdefined(P, k)
    )

    p0 = P.param0
    param0 = Dict{String,Any}(
        String(k) => getfield(p0, k) for k in fieldnames(typeof(p0))
    )

    cfg = Dict{String,Any}("ECG_Param" => ecg_param, "param0" => param0)
    isempty(setup) || (cfg["setup"] = setup)

    # actions (optional) — serialize the current ECG_Init.action_list, if ECG_Init
    # is loaded and holds any actions, via ECG_Init.actions_to_config().
    if include_actions && isdefined(parent, :ECG_Init) &&
       isdefined(parent.ECG_Init, :action_list) && isdefined(parent.ECG_Init, :actions_to_config)
        I = parent.ECG_Init
        if !isempty(I.action_list)
            cfg["actions"] = I.actions_to_config(I.action_list)
            verbose && println("save_config - wrote $(length(I.action_list)) action(s)")
        end
    end

    open(config_file, "w") do io
        JSON.print(io, cfg, 4)
    end
    verbose && println("save_config - wrote $config_file")
    return cfg
end

#------------------------------------------------------------------------------
# write_config_actions!() — update the "actions" array of the configuration file
# read by read_config (or `config_file`) with the current ECG_Init.action_list
# (via ECG_Init.actions_to_config), leaving the other sections untouched. Called
# by ECG.do_action() just before it writes inout_1.txt, so the configuration is
# ready to drive a follow-on run. Returns true if the file was updated; a no-op
# (returns false) if no config file was read, it no longer exists, or ECG_Init is
# unavailable.
#------------------------------------------------------------------------------
function write_config_actions!(action_list; config_file::AbstractString=_config_file[])
    isempty(config_file) && return false
    isfile(config_file)  || return false
    parent = parentmodule(@__MODULE__)
    (isdefined(parent, :ECG_Init) && isdefined(parent.ECG_Init, :actions_to_config)) || return false
    cfg = JSON.parsefile(config_file)
    cfg["actions"] = parent.ECG_Init.actions_to_config(action_list)
    open(config_file, "w") do io
        JSON.print(io, cfg, 4)
    end
    return true
end

end # module ECG_Config
